name: Deploy to EC2 - Nginx Server - AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      - name: Deploy to EC2
        run: |
          echo "Conectándose a la instancia de EC2..."
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Actualizando el contenido del repositorio..."
          cd /usr/share/nginx/html || exit
          git pull origin main
          echo "Reiniciando Nginx..."
          sudo systemctl restart nginx
          echo "Despliegue completado correctamente."
          EOF
