name: Deploy to EC2 - Nginx Server - AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      - name: Connection EC2 with EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} 
      - name: Connection EC2 with EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }}   
      - name: Update changes
        run: |
          cd /usr/share/nginx/html
          sudo git pull origin main
      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
