name: Deploy to EC2 - Nginx Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          echo "Conectándose a la instancia de EC2..."
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Actualizando el servidor..."
          pkill node || true
          cd ~/Actions-task-and-EC2 || exit
          git pull origin main
          npm install
          nohup node server.js > output.log 2>&1 &
          echo "Servidor reiniciado correctamente."
          EOF
